import {
  Transaction,
  Goal,
  CreditCard,
  BankAccount,
  FamilyMember,
} from '@/types'

// Função auxiliar para gerar IDs únicos
const generateId = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`

// Função auxiliar para criar datas nos últimos 3 meses
const getDateDaysAgo = (daysAgo: number): Date => {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date
}

// Dados mock de membros da família
export const mockFamilyMembers: FamilyMember[] = [
  {
    id: generateId('member'),
    name: 'Lucas Marte',
    role: 'Pai',
    avatarUrl: undefined,
    monthlyIncome: 8500,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: generateId('member'),
    name: 'Ana Marte',
    role: 'Mãe',
    avatarUrl: undefined,
    monthlyIncome: 6500,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: generateId('member'),
    name: 'Pedro Marte',
    role: 'Filho',
    avatarUrl: undefined,
    monthlyIncome: undefined,
    createdAt: new Date('2024-01-01'),
  },
]

// Dados mock de contas bancárias
export const mockBankAccounts: BankAccount[] = [
  {
    id: generateId('acc'),
    name: 'Nubank Conta',
    type: 'account',
    holderId: mockFamilyMembers[0].id,
    balance: 12500.50,
    createdAt: new Date('2023-12-01'),
  },
  {
    id: generateId('acc'),
    name: 'Itaú Conta Corrente',
    type: 'account',
    holderId: mockFamilyMembers[1].id,
    balance: 8500.00,
    createdAt: new Date('2023-11-15'),
  },
]

// Dados mock de cartões de crédito
export const mockCreditCards: CreditCard[] = [
  {
    id: generateId('cc'),
    name: 'Nubank Mastercard',
    type: 'creditCard',
    holderId: mockFamilyMembers[0].id,
    closingDay: 5,
    dueDay: 10,
    limit: 10000,
    currentBill: 3200.75,
    theme: 'black',
    lastDigits: '5897',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: generateId('cc'),
    name: 'Itaú Visa',
    type: 'creditCard',
    holderId: mockFamilyMembers[1].id,
    closingDay: 15,
    dueDay: 20,
    limit: 8000,
    currentBill: 1850.50,
    theme: 'lime',
    lastDigits: '4321',
    createdAt: new Date('2023-11-15'),
  },
  {
    id: generateId('cc'),
    name: 'Inter Elo',
    type: 'creditCard',
    holderId: mockFamilyMembers[0].id,
    closingDay: 25,
    dueDay: 5,
    limit: 5000,
    currentBill: 950.25,
    theme: 'white',
    lastDigits: '8765',
    createdAt: new Date('2023-10-10'),
  },
]

// Dados mock de transações (20-30 transações distribuídas nos últimos 3 meses)
export const mockTransactions: Transaction[] = [
  // Receitas
  {
    id: generateId('txn'),
    type: 'income',
    value: 8500,
    description: 'Salário Janeiro',
    category: 'Salário',
    date: getDateDaysAgo(45),
    accountId: mockBankAccounts[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'income',
    value: 6500,
    description: 'Salário Janeiro',
    category: 'Salário',
    date: getDateDaysAgo(45),
    accountId: mockBankAccounts[1].id,
    memberId: mockFamilyMembers[1].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'income',
    value: 2500,
    description: 'Freelance Projeto Web',
    category: 'Freelance',
    date: getDateDaysAgo(30),
    accountId: mockBankAccounts[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'income',
    value: 8500,
    description: 'Salário Fevereiro',
    category: 'Salário',
    date: getDateDaysAgo(15),
    accountId: mockBankAccounts[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'income',
    value: 6500,
    description: 'Salário Fevereiro',
    category: 'Salário',
    date: getDateDaysAgo(15),
    accountId: mockBankAccounts[1].id,
    memberId: mockFamilyMembers[1].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  // Despesas
  {
    id: generateId('txn'),
    type: 'expense',
    value: 2800,
    description: 'Supermercado Mensal',
    category: 'Mercado',
    date: getDateDaysAgo(40),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 350,
    description: 'Academia Mensal',
    category: 'Academia',
    date: getDateDaysAgo(38),
    accountId: mockCreditCards[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 1200,
    description: 'Aluguel',
    category: 'Aluguel',
    date: getDateDaysAgo(35),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 450,
    description: 'Contas de Luz e Água',
    category: 'Contas (água, luz, internet)',
    date: getDateDaysAgo(32),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 1800,
    description: 'Notebook Dell',
    category: 'Outros',
    date: getDateDaysAgo(28),
    accountId: mockCreditCards[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 6,
    status: 'completed',
    isRecurring: false,
    isPaid: false,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 250,
    description: 'Transporte Mensal',
    category: 'Transporte',
    date: getDateDaysAgo(25),
    accountId: mockBankAccounts[1].id,
    memberId: mockFamilyMembers[1].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 950,
    description: 'Material Escolar',
    category: 'Educação',
    date: getDateDaysAgo(22),
    accountId: mockBankAccounts[1].id,
    memberId: mockFamilyMembers[2].id,
    installments: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 1800,
    description: 'Supermercado Mensal',
    category: 'Mercado',
    date: getDateDaysAgo(10),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 350,
    description: 'Academia Mensal',
    category: 'Academia',
    date: getDateDaysAgo(8),
    accountId: mockCreditCards[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 420,
    description: 'Restaurante Final de Semana',
    category: 'Alimentação',
    date: getDateDaysAgo(5),
    accountId: mockCreditCards[1].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 1200,
    description: 'Aluguel',
    category: 'Aluguel',
    date: getDateDaysAgo(3),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: getDateDaysAgo(2),
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 150,
    description: 'Netflix Mensal',
    category: 'Lazer',
    date: getDateDaysAgo(1),
    accountId: mockCreditCards[0].id,
    memberId: null,
    installments: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 350,
    description: 'Academia Mensal',
    category: 'Academia',
    date: getDateDaysAgo(5),
    accountId: mockCreditCards[1].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: getDateDaysAgo(1),
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 450,
    description: 'Conta de Luz',
    category: 'Contas (água, luz, internet)',
    date: getDateDaysAgo(4),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 800,
    description: 'Supermercado Semanal',
    category: 'Mercado',
    date: getDateDaysAgo(2),
    accountId: mockCreditCards[0].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: false,
    isPaid: false,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 280,
    description: 'Spotify Mensal',
    category: 'Lazer',
    date: getDateDaysAgo(6),
    accountId: mockCreditCards[2].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 180,
    description: 'Plano de Celular',
    category: 'Contas (água, luz, internet)',
    date: getDateDaysAgo(1),
    accountId: mockCreditCards[1].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000), // 4 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 950,
    description: 'Farmácia',
    category: 'Saúde',
    date: getDateDaysAgo(3),
    accountId: mockBankAccounts[0].id,
    memberId: mockFamilyMembers[1].id,
    installments: 1,
    status: 'pending',
    isRecurring: false,
    isPaid: false,
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000), // 6 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 580,
    description: 'Conta de Água',
    category: 'Contas (água, luz, internet)',
    date: getDateDaysAgo(2),
    accountId: mockBankAccounts[0].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000), // 8 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 120,
    description: 'Amazon Prime',
    category: 'Lazer',
    date: getDateDaysAgo(4),
    accountId: mockCreditCards[0].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000), // 9 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 650,
    description: 'Material Escolar',
    category: 'Educação',
    date: getDateDaysAgo(1),
    accountId: mockCreditCards[1].id,
    memberId: mockFamilyMembers[2].id,
    installments: 1,
    status: 'pending',
    isRecurring: false,
    isPaid: false,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 420,
    description: 'Internet Mensal',
    category: 'Contas (água, luz, internet)',
    date: getDateDaysAgo(5),
    accountId: mockCreditCards[2].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // 10 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 750,
    description: 'Combustível',
    category: 'Transporte',
    date: getDateDaysAgo(2),
    accountId: mockCreditCards[0].id,
    memberId: mockFamilyMembers[0].id,
    installments: 1,
    status: 'pending',
    isRecurring: false,
    isPaid: false,
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // 1 dia a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 320,
    description: 'Seguro do Carro',
    category: 'Transporte',
    date: getDateDaysAgo(6),
    accountId: mockBankAccounts[1].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    dueDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000), // 11 dias a partir de hoje
  },
  {
    id: generateId('txn'),
    type: 'expense',
    value: 550,
    description: 'Restaurante Familiar',
    category: 'Alimentação',
    date: getDateDaysAgo(3),
    accountId: mockCreditCards[1].id,
    memberId: null,
    installments: 1,
    status: 'pending',
    isRecurring: false,
    isPaid: false,
    dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000), // 12 dias a partir de hoje
  },
]

// Dados mock de objetivos
export const mockGoals: Goal[] = [
  {
    id: generateId('goal'),
    title: 'Reserva de Emergência',
    description: 'Guardar 6 meses de despesas',
    targetAmount: 30000,
    currentAmount: 18500,
    deadline: new Date('2024-12-31'),
    memberId: null,
    category: 'Reserva',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: generateId('goal'),
    title: 'Férias em Família',
    description: 'Viagem para o Nordeste',
    targetAmount: 15000,
    currentAmount: 5200,
    deadline: new Date('2024-06-30'),
    memberId: null,
    category: 'Lazer',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: generateId('goal'),
    title: 'Novo Carro',
    description: 'Entrada para financiamento',
    targetAmount: 40000,
    currentAmount: 12000,
    deadline: new Date('2025-03-31'),
    memberId: mockFamilyMembers[0].id,
    category: 'Transporte',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: generateId('goal'),
    title: 'Educação Pedro',
    description: 'Fundos para faculdade',
    targetAmount: 50000,
    currentAmount: 8500,
    deadline: new Date('2027-01-31'),
    memberId: mockFamilyMembers[2].id,
    category: 'Educação',
    createdAt: new Date('2024-01-01'),
  },
]
